# datasource
spring:
  datasource:
    url: jdbc:mysql:///SpringBoot_Text?serverTimezone=UTC
    username: root
    password: 121206...
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #mapper映射文件路径
  type-aliases-package: com.yunsheng.springbootmybatis.domain
  #config-location:(指定mybatis的核心配置文件)
